### 1. Login first to get the session cookie
POST https://localhost:7250/login
Content-Type: application/json

{
    "email": "admin@codehive.com",
    "password": "Password123!"
}

### Full summary
GET https://localhost:7250/api/statistics/summary
Authorization: Bearer CfDJ8JSGQ0D973hAhmmfQIwPnZygCiEyosy3gqUCWJJ3-yBdarny4rvuz55tuF6kBHZGSHkYoVdP2-SBAmdeNhg9f_iMinj7QjQ7YjSopBN63OU10FafHP5e4UlxGKRcapE04lIZSQdFVOsQs06RUNrK8OhaU43pgOBK8GBg4_zALjmyFXScYoJGdfFoE9iKMFem8LefUAgsEq0UN8qAFAUXD0zaeZRjcXUFSc7RPvGps766WKyK0VoDmKe0P4BdhO7Q2Ydw_zdnPlphASmDe3cTq0-ybyyAliDVUTBSxooENQcYkKDL3e1Ivps7bcTEzyk-SzUYvpSoccMs8LCp0InOQPD-HJrPelqNhJz1ylSW7JjIY3VcVIrH70ilCmIifoxvUVh-dh3I68B8U4MfUGekiYtv6UktsDEDFuSR7lQSn3ldq5mS1JDzua4fq1W-sA8m-Fse-8ODwUa6xKbofa_mt6iRQRhtDaYC-OBhg4Fld8qPyF20n5RwKhVvmVQzG-VLbgHzVysIbGxczm8ZK5HMgHMHMJTjLcsvcNAfUJNZ5xz_LSJtfQoPnammahTUsygvgoheh4t2N_hUOSsBYYBqBDnlxzBQFq-uy8EpUZO7W5_8Yxl_PRaEDhCfr1MNW0LKEvLeiwBbazUacZiQCfEefQEQIDPI3eSuR3QEsfN7h1leeI88Gqu5LKmo7l3ksRsy3ZaLHJ_r-sfg69jfiAE_mJo

### dates

### Create Inventory
POST https://localhost:7250/api/inventory
Authorization: Bearer CfDJ8JSGQ0D973hAhmmfQIwPnZwjoPjUXOPFBx6UA8ZvJvLCz8P49q5jEohg5HeR1r6013Mapcb75eDNQp2JEsiXRAonY6hg2VP5WkdeMdv51KSP4BxoJtp7CrV0sNwFDUWiwCoFvNUfjPkPtKQs8POEeAsUPc9pA__V2cF4Lt98QW4hh1WDr4NIrNwHTAf6b9-WiEOzW3OvmceE1-fJxVC04drs3ElSHedG4J7HRus64sfG2e7vkubo34UBfmHqJt8ZRPQzqmWDZ3t5wV16g7zWFlCuC2FNM1ew7l5TfXi6jPJxHQkbIjYHWrWWNiKBbaTWLJzcsOMyDSMnjbQA9P8S1sQgyZQynW9Y7YVZHEdCESLmWDBOJ-VTNKD1sUKuNVw8u2I4lim4n27HGDdSHQGFic3JI7DE91lkv7kxTrlcWXjXMLGZFQBM10lWx2fxI39WIkX4Z1sub4WtZtDZnMAarIcoUIwPWniy3p2Ji2LcAFp4OHs-IHBcOWme9Xi3nZsCWndQh3KWf2Y8UdfZcvUoCK8BghK6u-w-vDlRr60q0JayTRe0XEvb7PC2nAfz9kksFG5cjldMP-0ApDyA5sTj_cbceRm62SlwlVmnB6DrNI46dHyB0Fk6hAcBDPPuNgDBvTJFr1SFxzzCZVh_OgeA5gNI4aAI6u4LtkvQ2gKKz_GHlliC_Rxt2NO4rg6mbuHUzHEsPYUWmxrCVlmiDKdJX9s
Content-Type: application/json

{
"name": "Notebook",
"quantityInStock": 10,
"reorderLevel": 2,
"unitPrice": 5.00
}

### The product
GET https://localhost:7250/api/services
Authorization: Bearer CfDJ8JSGQ0D973hAhmmfQIwPnZwjoPjUXOPFBx6UA8ZvJvLCz8P49q5jEohg5HeR1r6013Mapcb75eDNQp2JEsiXRAonY6hg2VP5WkdeMdv51KSP4BxoJtp7CrV0sNwFDUWiwCoFvNUfjPkPtKQs8POEeAsUPc9pA__V2cF4Lt98QW4hh1WDr4NIrNwHTAf6b9-WiEOzW3OvmceE1-fJxVC04drs3ElSHedG4J7HRus64sfG2e7vkubo34UBfmHqJt8ZRPQzqmWDZ3t5wV16g7zWFlCuC2FNM1ew7l5TfXi6jPJxHQkbIjYHWrWWNiKBbaTWLJzcsOMyDSMnjbQA9P8S1sQgyZQynW9Y7YVZHEdCESLmWDBOJ-VTNKD1sUKuNVw8u2I4lim4n27HGDdSHQGFic3JI7DE91lkv7kxTrlcWXjXMLGZFQBM10lWx2fxI39WIkX4Z1sub4WtZtDZnMAarIcoUIwPWniy3p2Ji2LcAFp4OHs-IHBcOWme9Xi3nZsCWndQh3KWf2Y8UdfZcvUoCK8BghK6u-w-vDlRr60q0JayTRe0XEvb7PC2nAfz9kksFG5cjldMP-0ApDyA5sTj_cbceRm62SlwlVmnB6DrNI46dHyB0Fk6hAcBDPPuNgDBvTJFr1SFxzzCZVh_OgeA5gNI4aAI6u4LtkvQ2gKKz_GHlliC_Rxt2NO4rg6mbuHUzHEsPYUWmxrCVlmiDKdJX9s
Content-Type: application/json

{
  "name": "Premium Day Pass",
  "description": "Includes a free notebook",
  "price": 35.00,
  "isAvailable": true,
  "inventoryItemId": "019b9a86-6db3-7722-bbf5-cfde5497edb0"
}

### Put request
PUT https://localhost:7250/api/services/019b9a7b-5aca-7b2c-afa5-fe60a167b910
Authorization: Bearer CfDJ8JSGQ0D973hAhmmfQIwPnZwjoPjUXOPFBx6UA8ZvJvLCz8P49q5jEohg5HeR1r6013Mapcb75eDNQp2JEsiXRAonY6hg2VP5WkdeMdv51KSP4BxoJtp7CrV0sNwFDUWiwCoFvNUfjPkPtKQs8POEeAsUPc9pA__V2cF4Lt98QW4hh1WDr4NIrNwHTAf6b9-WiEOzW3OvmceE1-fJxVC04drs3ElSHedG4J7HRus64sfG2e7vkubo34UBfmHqJt8ZRPQzqmWDZ3t5wV16g7zWFlCuC2FNM1ew7l5TfXi6jPJxHQkbIjYHWrWWNiKBbaTWLJzcsOMyDSMnjbQA9P8S1sQgyZQynW9Y7YVZHEdCESLmWDBOJ-VTNKD1sUKuNVw8u2I4lim4n27HGDdSHQGFic3JI7DE91lkv7kxTrlcWXjXMLGZFQBM10lWx2fxI39WIkX4Z1sub4WtZtDZnMAarIcoUIwPWniy3p2Ji2LcAFp4OHs-IHBcOWme9Xi3nZsCWndQh3KWf2Y8UdfZcvUoCK8BghK6u-w-vDlRr60q0JayTRe0XEvb7PC2nAfz9kksFG5cjldMP-0ApDyA5sTj_cbceRm62SlwlVmnB6DrNI46dHyB0Fk6hAcBDPPuNgDBvTJFr1SFxzzCZVh_OgeA5gNI4aAI6u4LtkvQ2gKKz_GHlliC_Rxt2NO4rg6mbuHUzHEsPYUWmxrCVlmiDKdJX9s
Content-Type: application/json

{
  "id": "019b9a7b-5aca-7b2c-afa5-fe60a167b910",
  "name": "Day Pass with Notebook",
  "description": "Desk plus Notebook",
  "price": 25.0,
  "isAvailable": true,
  "inventoryItemId": "019b9a86-6db3-7722-bbf5-cfde5497edb0"
}

### The sale
POST https://localhost:7250/api/orders
Authorization: Bearer CfDJ8JSGQ0D973hAhmmfQIwPnZwjoPjUXOPFBx6UA8ZvJvLCz8P49q5jEohg5HeR1r6013Mapcb75eDNQp2JEsiXRAonY6hg2VP5WkdeMdv51KSP4BxoJtp7CrV0sNwFDUWiwCoFvNUfjPkPtKQs8POEeAsUPc9pA__V2cF4Lt98QW4hh1WDr4NIrNwHTAf6b9-WiEOzW3OvmceE1-fJxVC04drs3ElSHedG4J7HRus64sfG2e7vkubo34UBfmHqJt8ZRPQzqmWDZ3t5wV16g7zWFlCuC2FNM1ew7l5TfXi6jPJxHQkbIjYHWrWWNiKBbaTWLJzcsOMyDSMnjbQA9P8S1sQgyZQynW9Y7YVZHEdCESLmWDBOJ-VTNKD1sUKuNVw8u2I4lim4n27HGDdSHQGFic3JI7DE91lkv7kxTrlcWXjXMLGZFQBM10lWx2fxI39WIkX4Z1sub4WtZtDZnMAarIcoUIwPWniy3p2Ji2LcAFp4OHs-IHBcOWme9Xi3nZsCWndQh3KWf2Y8UdfZcvUoCK8BghK6u-w-vDlRr60q0JayTRe0XEvb7PC2nAfz9kksFG5cjldMP-0ApDyA5sTj_cbceRm62SlwlVmnB6DrNI46dHyB0Fk6hAcBDPPuNgDBvTJFr1SFxzzCZVh_OgeA5gNI4aAI6u4LtkvQ2gKKz_GHlliC_Rxt2NO4rg6mbuHUzHEsPYUWmxrCVlmiDKdJX9s
Content-Type: application/json

{
"staffId": "019b9a19-bb45-7ed8-93e2-7349a8d66535",
"businessServiceId": "019b9a7b-5aca-7b2c-afa5-fe60a167b910",
"customerName": "John Doe",
"quantity": 8,
"totalPrice": 150.00
}

### Checking Inventory
GET https://localhost:7250/api/inventory
///Authorization: Bearer CfDJ8JSGQ0D973hAhmmfQIwPnZwjoPjUXOPFBx6UA8ZvJvLCz8P49q5jEohg5HeR1r6013Mapcb75eDNQp2JEsiXRAonY6hg2VP5WkdeMdv51KSP4BxoJtp7CrV0sNwFDUWiwCoFvNUfjPkPtKQs8POEeAsUPc9pA__V2cF4Lt98QW4hh1WDr4NIrNwHTAf6b9-WiEOzW3OvmceE1-fJxVC04drs3ElSHedG4J7HRus64sfG2e7vkubo34UBfmHqJt8ZRPQzqmWDZ3t5wV16g7zWFlCuC2FNM1ew7l5TfXi6jPJxHQkbIjYHWrWWNiKBbaTWLJzcsOMyDSMnjbQA9P8S1sQgyZQynW9Y7YVZHEdCESLmWDBOJ-VTNKD1sUKuNVw8u2I4lim4n27HGDdSHQGFic3JI7DE91lkv7kxTrlcWXjXMLGZFQBM10lWx2fxI39WIkX4Z1sub4WtZtDZnMAarIcoUIwPWniy3p2Ji2LcAFp4OHs-IHBcOWme9Xi3nZsCWndQh3KWf2Y8UdfZcvUoCK8BghK6u-w-vDlRr60q0JayTRe0XEvb7PC2nAfz9kksFG5cjldMP-0ApDyA5sTj_cbceRm62SlwlVmnB6DrNI46dHyB0Fk6hAcBDPPuNgDBvTJFr1SFxzzCZVh_OgeA5gNI4aAI6u4LtkvQ2gKKz_GHlliC_Rxt2NO4rg6mbuHUzHEsPYUWmxrCVlmiDKdJX9s
